[package]
name = "pstruct_rust"
version = "0.3.0"
authors = ["wwared"]
edition = "2021"

[[test]]
name= "tests"
path = "tests/mod.rs"

[dependencies]
quote = "1.0.7"
proc-macro2 = "1"

pstruct = { path = "../../pstruct" }
